export const REPORT_LOCATION = 'REPORT_LOCATION';
export const REPORT_LINE = 'REPORT_LINE';

export const FETCH_LINES_START = 'FETCH_LINES_START';
export const FETCH_LINES_SUCCESS = 'FETCH_LINES_SUCCESS';
export const FETCH_LINES_FAIL = 'FETCH_LINES_FAIL';