export const REPORT_LOCATION_START = 'REPORT_LOCATION_START';
export const REPORT_LOCATION_SUCCESS = 'REPORT_LOCATION_SUCCESS';
export const REPORT_LOCATION_FAIL = 'REPORT_LOCATION_FAIL';

export const REPORT_LINE_START = 'REPORT_LINE_START';
export const REPORT_LINE_SUCCESS = 'REPORT_LINE_SUCCESS';
export const REPORT_LINE_FAIL = 'REPORT_LINE_FAIL';

export const FETCH_LINES_START = 'FETCH_LINES_START';
export const FETCH_LINES_SUCCESS = 'FETCH_LINES_SUCCESS';
export const FETCH_LINES_FAIL = 'FETCH_LINES_FAIL';